spring.application.name=dino
spring.jpa.hibernate.ddl-auto=update

# Credenciales y Rutas para Debuguear Localmente desde tu IDE (Localhost)
# (Cuando corras en Docker, estas rutas serán ignoradas y reemplazadas por las del compose.yaml de forma automática)
spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=3000ms
spring.rabbitmq.listener.simple.retry.multiplier=2.0

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.ar.com.froneus.challenge=INFO
spring.jackson.serialization.write-dates-as-timestamps=false
